#! /bin/sh -e
# Create plot for today's code.

STAMP=$(date +"%Y%m%d")

go clean
go install

N="
1000
10000
25000
50000
"

rm -f data.$STAMP
for n in $N; do
	echo "Running with $n commands ..."
set -x
	seconds=$((time -p cqrsprof -e $n) 2>&1 | grep real |awk '{print $2}')
set +x
	printf "%s\t%8.2f\n" $n $seconds >> data.$STAMP
done
